export const gifts = [
  {
    name: '쉘 퍼퓸 핸드 카모',
    url: 'https://www.tamburins.com/kr/item/1666763525/',
    image_url:
      'https://web-resource.tamburins.com/catalog/product/1666763525/9a4c263e-7030-4038-8c4c-5cfc07488dcc/thumbnail_Shell_30ml_Chamo.jpg',
    category: ['뷰티'],
    emotion_keywords: ['차분함', '절제됨', '세련됨'],
    action_keywords: ['조용히 건네기', '퇴근 후 손에 바르기'],
    scene_keywords: ['잔잔한 저녁 조명 아래', '늦가을 바람이 부는 창가'],
    expression_keywords: ['향기로 위로 전하기', '말 대신 손끝으로 감정 전달'],
    recommended_relations: ['동료', '연인', '상사'],
    recommended_occasions: ['감사', '응원', '격려'],
    mood_summary: '묵묵히 곁에 있어주는 사람에게, 따뜻한 잔향으로 감정을 전하는 선물입니다.',
    target_age: '30대',
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '마뗑킴 아코디언 월렛 블랙',
    url: 'https://m.matinkim.com/product/accordion-wallet-in-black/2164/',
    image_url:
      'https://m.matinkim.com/web/product/medium/202209/9f7ebe5f302120d1bc1e407392992005.jpg',
    category: ['리빙/라이프스타일', '패션'],
    emotion_keywords: ['세련됨', '고급스러움', '정돈됨', '실용성'],
    action_keywords: ['가방에서 꺼내기', '카드 정리하기'],
    scene_keywords: ['도심의 세련된 카페에서', '업무 회의 후'],
    expression_keywords: ['스타일로 감성을 전하다', '작은 소품으로 세련됨 표현'],
    recommended_relations: ['친구', '동료', '연인', '상사'],
    recommended_occasions: ['생일', '감사', '축하', '승진'],
    mood_summary:
      '고급스러운 디자인과 실용성이 돋보이는 지갑은 세련된 도시 생활을 즐기는 이들에게 안성맞춤입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '7-9만원대',
    target_gender: '여성',
  },
  {
    name: '지니오 S 쉐어 크림 스타벅스 앳홈 팩',
    url: 'https://www.dolce-gusto.co.kr/machines/genio-s/genio-s-share-cream-bundle-pack',
    image_url:
      'https://www.dolce-gusto.co.kr/media/catalog/product/cache/7ddbd16ffa03168d51e4faffbd564ba7/_/_/____241105_2.png',
    category: ['디저트/카페', '리빙/라이프스타일'],
    emotion_keywords: ['편안함', '호기심', '일상의 즐거움'],
    action_keywords: ['함께 마시며 이야기 나누기', '일과 중간 쉼표'],
    scene_keywords: ['느긋한 주말 아침', '서늘한 오후의 테라스'],
    expression_keywords: ['향으로 마음을 녹이기', '소소한 일상의 특별함 나누기'],
    recommended_relations: ['친구', '동료', '부모님'],
    recommended_occasions: ['생일', '감사', '축하', '따뜻한 위로'],
    mood_summary:
      '즐거운 대화를 위한 여유로운 커피 타임이 필요한 순간, 특별한 향과 맛으로 마음을 전합니다.',
    target_age: ['20대', '30대', '40대'],
    price: '20만원대',
    target_gender: '성별 무관',
  },
  {
    name: '헤라 블랙 쿠션 파운데이션',
    url: 'https://www.hera.com/kr/ko/products/black-cushion-foundation.html',
    image_url:
      'https://www.hera.com/kr/ko/products/__icsFiles/afieldfile/2024/08/29/240318_final_KR_BLACK-CUSHION-FOUNDATION_pdp_thumbnail_13N1_1.jpg',
    category: ['뷰티'],
    emotion_keywords: ['자신감', '세련됨', '완벽함'],
    action_keywords: ['아침 외출 준비', '중요한 약속 전 사용하는'],
    scene_keywords: ['분주한 아침 화장대 앞', '빛나는 저녁 파티 전'],
    expression_keywords: ['작은 디테일로 큰 변화를 선사', '완벽한 하루를 위한 마무리'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '축하', '응원'],
    mood_summary: '섬세한 디테일로 하루를 빛나게 하며 중요한 날 자신감을 더해주는 선물',
    target_age: ['20대', '30대'],
    price: '7-9만원대',
    target_gender: '여성',
  },
  {
    name: '젠틀몬스터 DUNNS 01',
    url: 'https://www.gentlemonster.com/kr/ko/item/10S4IJHEFGR2A/duns-01',
    image_url:
      'https://gm-prd-resource.gentlemonster.com/catalog/product/bulk/3c0dbc33-811f-49cc-b099-418243894828/10S4IJHEFGR2A_FRONT.jpg',
    category: ['패션', '아이웨어'],
    emotion_keywords: ['모던함', '세련됨', '자신감'],
    action_keywords: ['외출 준비할 때 쓰기', '주말 나들이 때 쓰기'],
    scene_keywords: ['맑은 날씨의 거리', '도시의 카페 테라스'],
    expression_keywords: ['스타일의 완성 선물하기', '개성을 돋보이게 하기'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '기념일', '축하'],
    mood_summary: '스타일리시한 모던함을 전하며, 특별한 날의 자신감을 채워주는 아이템.',
    target_age: ['20대', '30대'],
    price: '30만원대',
    target_gender: '성별 무관',
  },
  {
    name: '디불 고급 차량용 방향제 자동차 디퓨저',
    url: 'https://deproject.co.kr/product/%EB%94%94%EB%B6%88-%EA%B3%A0%EA%B8%89-%EC%B0%A8%EB%9F%89%EC%9A%A9-%EB%B0%A9%ED%96%A5%EC%A0%9C-%EC%9E%90%EB%8F%99%EC%B0%A8-%EB%94%94%ED%93%A8%EC%A0%80db/22/category/48/display/1/',
    image_url:
      'https://cafe24.poxo.com/ec01/deofficial/fYw07Q+e08011Z5Qzbz30/inZiKFihqRAaeqTNBEyW9XiA5NQOlo8uBI2wVOq/NUZGU1sHgoNSTc2+hnpuGq9w==/_/web/product/extra/small/202304/36792f09ecd96bc76295fccb1c6c7364.jpg',
    category: ['리빙/라이프스타일', '자동차용품'],
    emotion_keywords: ['산뜻함', '여유', '세련됨'],
    action_keywords: ['차량 내 설치하기', '장거리 운전 시 사용'],
    scene_keywords: ['출근길 아침', '드라이브 중'],
    expression_keywords: ['향기로 기억에 남기기', '탐스러운 세련미 선사'],
    recommended_relations: ['친구', '상사'],
    recommended_occasions: ['생일', '감사', '승진 축하'],
    mood_summary: '여유로운 드라이브를 즐기는 순간을 향기로 채우며 세련된 분위기를 더해줍니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '남성',
  },
  {
    name: '인스탁스 미니 리플레이',
    url: 'https://brand.naver.com/instax/products/4790192176',
    image_url:
      'https://shop-phinf.pstatic.net/20240517_235/1715906796549EPGEB_PNG/117042685227497002_1960471407.png?type=m510',
    category: ['리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['추억', '즉흥적임', '창의성'],
    action_keywords: ['사진 찍기', '추억 남기기'],
    scene_keywords: ['축제 속 열기', '여행 중 순간 포착'],
    expression_keywords: ['순간의 아름다움 기록', '즉각적 기쁨 전달'],
    recommended_relations: ['친구', '연인'],
    recommended_occasions: ['생일', '기념일', '여행 출발 전'],
    mood_summary:
      '잊을 수 없는 순간들을 즉석에서 기록하고 공유하며, 감성적인 추억을 함께 만들어요.',
    target_age: ['10대', '20대', '30대'],
    price: '20만원대',
    target_gender: '성별 무관',
  },
  {
    name: '센티카 필로우 미스트 네롤리샤워 200ml',
    url: 'https://brand.naver.com/scentica/products/11525712324',
    image_url:
      'https://shop-phinf.pstatic.net/20250226_50/1740559803409o7CED_JPEG/12452972365912586_1982748489.jpg?type=m510',
    category: ['뷰티', '리빙/라이프스타일'],
    emotion_keywords: ['평온함', '휴식', '상쾌함'],
    action_keywords: ['베개에 뿌리기', '자기 전 사용'],
    scene_keywords: ['편안한 저녁 시간', '일과 후의 집'],
    expression_keywords: ['향기로 기억에 남기기', '안락함 전달'],
    recommended_relations: ['연인', '친구', '부모님'],
    recommended_occasions: ['생일', '감사', '응원'],
    mood_summary: '하루의 피로를 잊게 해주는 상쾌한 네롤리 향으로 편안한 밤을 선사합니다.',
    target_age: ['20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '성별 무관',
  },
  {
    name: '조말론 라임 바질 앤 만다린 코롱',
    url: 'https://www.jomalone.co.kr/product/25946/10101/lime-basil-mandarin-cologne',
    image_url:
      'https://www.jomalone.co.kr/media/export/cms/products/1000x1000/jo_sku_L00401_1000x1000_0.png',
    category: ['뷰티', '리빙/라이프스타일'],
    emotion_keywords: ['신선함', '시원함', '세련됨', '활력', '청량감'],
    action_keywords: ['아침에 뿌리기', '산뜻함을 느끼기'],
    scene_keywords: ['여름날 해변 산책', '도심 속 카페 테라스'],
    expression_keywords: ['상쾌한 하루의 시작', '활기를 불어넣기'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '감사', '축하', '응원'],
    mood_summary: '무더운 여름날의 신선한 활력을 전하며, 도시의 세련됨과 청량감을 선사합니다.',
    target_age: ['20대', '30대', '40대'],
    price: '20만원대',
    target_gender: '여성',
  },
  {
    name: '크로우캐넌 마블 머그 2P 세트',
    url: 'https://crowcanyon.co.kr/product/%EB%A7%88%EB%B8%94-%EB%A8%B8%EA%B7%B8-2p-%EC%84%B8%ED%8A%B8/4040/category/382/display/1/',
    image_url:
      'https://crowcanyon.co.kr/web/product/big/202502/b0e831e7491dad38999ab3bb1683b2f0.jpg',
    category: ['리빙/라이프스타일', '디저트/카페'],
    emotion_keywords: ['심플함', '편안함', '일상의 소소함'],
    action_keywords: ['친구와의 커피 타임', '느긋한 아침'],
    scene_keywords: ['따뜻한 아침 햇살 아래', '비오는 날의 오후'],
    expression_keywords: ['일상 속의 작은 행복 나누기', '함께 하는 순간 소중히 하기'],
    recommended_relations: ['친구', '동료', '연인'],
    recommended_occasions: ['신혼집 선물', '이사 축하', '소소한 감사의 표현'],
    mood_summary: '심플한 디자인의 머그로 일상의 작은 순간을 특별하게 만들기 좋은 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '닥터 브라이언 복숭아맛구미 비타민C&D 3000(100구미) x 2ea',
    url: 'https://m.drbrianmall.com/product/%EB%8B%A5%ED%84%B0%EB%B8%8C%EB%9D%BC%EC%9D%B4%EC%96%B8-%EB%B3%B5%EC%88%AD%EC%95%84%EB%A7%9B%EA%B5%AC%EB%AF%B8-%EB%B9%84%ED%83%80%EB%AF%BCcd-3000100%EA%B5%AC%EB%AF%B8-x-2ea/308/category/123/display/1/',
    image_url:
      'https://ecimg.cafe24img.com/pg700b10253640048/drbrianmall/web/product/big/20240809/3a73894fc4f5209e80904ed5d51f9c06.png',
    category: ['건강'],
    emotion_keywords: ['상쾌함', '상냥함', '발랄함'],
    action_keywords: ['서프라이즈 선물하기', '조금씩 나눠 먹기'],
    scene_keywords: ['맑은 아침 식탁', '봄날 피크닉', '친구들과의 주말 브런치'],
    expression_keywords: ['작은 배려로 전하기', '달콤한 기분을 전하기'],
    recommended_relations: ['친구', '동료', '부모님', '상사'],
    recommended_occasions: ['감사', '응원', '작은 기쁨 나누기'],
    mood_summary:
      '일상의 스트레스에서 달콤하고 건강하게 벗어나고 싶은 분께, 파릇파릇한 기분을 전하세요.',
    target_age: ['20대', '30대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '딥퍼랑스 퍼퓸 핸드크림 50ml [그리너리 & 바질]',
    url: 'https://deeperence.com/24/?idx=209',
    image_url: 'https://cdn.imweb.me/thumbnail/20240919/ceea76e4c2fb4.jpg',
    category: ['뷰티', '리빙/라이프스타일'],
    emotion_keywords: ['상쾌함', '자연스러움', '신선함'],
    action_keywords: ['손을 가볍게 마사지하기', '산뜻한 기운 전하기'],
    scene_keywords: ['봄의 숲속 산책길에서', '창가에서의 차 한 잔 시간'],
    expression_keywords: ['자연의 향으로 감싸안기', '선물로 상쾌함 전하기'],
    recommended_relations: ['친구', '동료', '연인'],
    recommended_occasions: ['생일', '감사', '축하'],
    mood_summary:
      '자연의 신선함이 깃든 향기로 일상에 청량감을 선사할 수 있는 사람에게 어울리는 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '여성',
  },
  {
    name: '아스파시아플라워 비누꽃 꽃다발',
    url: 'https://smartstore.naver.com/pum/products/6632407728?nl-query=%EC%95%84%EC%8A%A4%ED%8C%8C%EC%8B%9C%EC%95%84%ED%94%8C%EB%9D%BC%EC%9B%8C%20%EB%B9%84%EB%88%84%EA%BD%83&nl-au=16c1a057712346fe826be8c1d336fb63&NaPm=ci%3D16c1a057712346fe826be8c1d336fb63%7Cct%3Dma8bxfwc%7Ctr%3Dnslsl%7Csn%3D159185%7Chk%3D455f17dcdc4542820e808c898bf4a5844538c7b4',
    image_url:
      'https://shop-phinf.pstatic.net/20220627_229/1656314485259a8eaz_JPEG/57450373970757968_1710368331.jpg?type=m510',
    category: ['리빙/라이프스타일', '뷰티'],
    emotion_keywords: ['로맨틱함', '부드러움', '세련됨', '따뜻함'],
    action_keywords: ['기념일에 전달하기', '특별한 날 장식용으로 사용하기'],
    scene_keywords: ['햇살 가득한 거실에 놓인', '저녁 식탁에 놓인 꽃다발'],
    expression_keywords: ['시각과 후각으로 감성 전하기', '우아한 아름다움으로 마음 전하기'],
    recommended_relations: ['연인', '친구', '부모님'],
    recommended_occasions: ['발렌타인데이', '기념일', '축하'],
    mood_summary:
      '이 비누꽃 꽃다발은 특별한 날 서로의 마음을 따뜻하게 전할 수 있는 섬세하고 우아한 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '여성',
  },
  {
    name: '빌리엔젤 레드벨벳 케이크',
    url: 'https://www.billyangel.com/shop/shopdetail.html?branduid=199&xcode=002&mcode=001&scode=&type=Y&sort=sellcnt&cur_code=002001&search=&GfDT=bmh8W1g%3D',
    image_url: 'https://www.billyangel.com/shopimages/billyangel/0010000001992.jpg?1735196269',
    category: ['디저트/카페'],
    emotion_keywords: ['달콤함', '기쁨', '부드러움', '설렘', '축하'],
    action_keywords: ['함께 나누기', '소중한 사람에게 건네기'],
    scene_keywords: ['오후 티타임', '생일 파티에서', '작은 모임에서'],
    expression_keywords: ['달콤한 맛으로 기쁨 전달', '부드러운 식감으로 마음 전하기'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '축하', '감사'],
    mood_summary:
      '달콤하고 부드러운 레드벨벳 케이크는 특별한 날 기쁨을 나누기에 완벽한 선택입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: 'Kodak 코닥 일회용 플래시 카메라 / 펀 세이버 39 / Fun Saver',
    url: 'https://smartstore.naver.com/coredak/products/4785024689',
    image_url:
      'https://shop-phinf.pstatic.net/20230309_236/1678356887222OXhnk_JPEG/79492775933138141_1309223572.jpg?type=m510',
    category: ['여행용품', '리빙/라이프스타일'],
    emotion_keywords: ['향수', '즐거움', '추억', '탐험정신'],
    action_keywords: ['즐거운 순간 포착하기', '즉흥적으로 사진 찍기'],
    scene_keywords: ['여행 중에 만난 절경 앞에서', '친구들과의 공유하는 즐거운 밤'],
    expression_keywords: ['순간을 사진으로 남기기', '즉석에서 즐거움을 공유하기'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['여행', '특별한 날 기념', '즉흥적인 모임'],
    mood_summary: '중요한 순간들을 필름에 담아 추억으로 간직할 수 있는 카메라입니다.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '러쉬 카마 솔리드 퍼퓸',
    url: 'https://www.lush.co.kr/m/products/view/273?giftYn=Y&dc=',
    image_url: 'https://www.lush.co.kr/upload/item/273/20241118112129L.png',
    category: ['뷰티'],
    emotion_keywords: ['관능적임', '열정적임', '유혹적임'],
    action_keywords: ['손목에 살짝 바르기', '데이트 전 사용'],
    scene_keywords: ['밤 하늘 아래 도시 거리', '친밀한 저녁 식사 자리'],
    expression_keywords: ['향으로 유혹하기', '매력을 강조하기'],
    recommended_relations: ['연인', '친구'],
    recommended_occasions: ['기념일', '특별한 저녁', '데이트'],
    mood_summary:
      '이 제품은 감각적인 향기로 특별한 순간에 매혹적인 분위기를 더할 수 있는 소중한 선물입니다.',
    target_age: ['20대', '30대'],
    price: '3만원대',
    target_gender: '여성',
  },
  {
    name: '샤넬 보이 드 샤넬 모이스처라이징 매트 립밤',
    url: 'https://www.chanel.com/kr/makeup/p/195050/boy-de-chanel-lip-balm/',
    image_url:
      'https://www.chanel.com/images//t_one//w_0.38,h_0.38,c_crop/q_auto:good,f_autoplus,fl_lossy,dpr_1.1/w_1240/boy-de-chanel-lip-balm-0-1oz--packshot-default-195050-9564827090974.jpg',
    category: ['뷰티'],
    emotion_keywords: ['절제된 세련미', '편안함', '정교함'],
    action_keywords: ['매일 아침 루틴에 추가하기', '외출 전 간편하게 사용'],
    scene_keywords: ['도시의 바쁜 아침', '여유로운 주말 브런치'],
    expression_keywords: ['세련된 감각을 선물하기', '작은 세심함으로 표현'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '감사', '응원'],
    mood_summary:
      '절제된 세련미로 하루를 새롭게 시작하고 싶은 이들에게 자연스럽게 내면의 자신감을 더해줍니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '아로마티카 Sleep Tight Pillow Mist 슬립타이트 필로우 미스트 100ML',
    url: 'https://aromatica.co.kr/product/detail.html?product_no=1942&cate_no=1&display_group=23',
    image_url:
      'https://aromatica.co.kr/web/product/extra/small/202211/ca8512a74f892fbd996d7756c224c6c3.jpg',
    category: ['뷰티', '리빙/라이프스타일', '건강'],
    emotion_keywords: ['안정', '편안함', '포근함', '휴식'],
    action_keywords: ['잠자기 전 뿌리기', '긴 하루 후 휴식'],
    scene_keywords: ['촛불이 켜진 저녁', '물결이 잔잔한 나의 방'],
    expression_keywords: ['향기로 기억에 남기기', '소중함을 전하기'],
    recommended_relations: ['연인', '친구', '부모님', '동료'],
    recommended_occasions: ['생일', '감사', '집들이', '응원'],
    mood_summary:
      '아로마티카 슬립 타이트 필로우 미스트는 편안한 숙면을 위한 향기를 전해줘서 수면의 질을 높이고 싶은 이들에게 따뜻한 마음을 전할 수 있는 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '프로젝트 슬립 라포즈 필로우 미스트',
    url: 'https://www.projectsleep.co.kr/goods/goods_view.php?goodsNo=1000000111',
    image_url:
      'https://cdn-pro-web-151-250.cdn-nhncommerce.com/projectr1936_godomall_com/data/goods/23/03/10/1000000111/1000000111_detail_033.jpg',
    category: ['리빙/라이프스타일', '건강'],
    emotion_keywords: ['편안함', '안정감', '포근함', '휴식', '상쾌함'],
    action_keywords: ['자기 전 뿌리기', '마음 전하기', '휴식 공간 준비'],
    scene_keywords: ['잠들기 전 고요한 침실', '바쁜 하루의 마무리 후', '여유로운 주말 아침'],
    expression_keywords: ['조용한 관심 표현', '향기로 마음 전하기'],
    recommended_relations: ['연인', '친구', '부모님', '동료'],
    recommended_occasions: ['생일', '감사', '응원', '휴식 필요할 때'],
    mood_summary: '하루의 피로를 잊고 싶을 때, 마음을 차분하게 만들어 줄 특별한 시간.',
    target_age: ['20대', '30대', '40대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '프로젝트 슬립 양면안대',
    url: 'https://www.projectsleep.co.kr/goods/goods_view.php?goodsNo=1000000029',
    image_url:
      'https://godomall.speedycdn.net/bdb28a964a8fad114e26f0c91ba40c35/goods/1000000029/image/detail/thumb/1000000029_detail_047.jpg',
    category: ['건강', '리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['편안함', '안정감', '휴식', '포근함', '정적'],
    action_keywords: ['잠들기 전 착용하기', '여행 중 휴식 때 사용하기'],
    scene_keywords: ['조용한 밤 침실', '장거리 비행 중 비행기 좌석', '낮잠이 필요한 오후'],
    expression_keywords: ['따뜻한 배려로 표현', '작은 휴식을 선물'],
    recommended_relations: ['연인', '친구', '부모님', '동료'],
    recommended_occasions: ['감사', '응원', '생일', '여행 준비'],
    mood_summary: '편안한 숙면과 휴식을 통해 소중한 사람에게 따뜻한 배려를 전하세요.',
    target_age: ['20대', '30대', '40대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '비타그램 눈찜질 온열스팀 수면안대 눈마사지기 VG-1002 골드아이 베이지 USB 온열안대',
    url: 'https://brand.naver.com/vitagram/products/2302472443',
    image_url:
      'https://shop-phinf.pstatic.net/20231221_134/1703146116958bi8vs_JPEG/104282005658010895_848617106.jpg?type=o1000',
    category: ['리빙/라이프스타일', '건강', '여행용품'],
    emotion_keywords: ['편안함', '휴식', '안정감', '따뜻함', '충전'],
    action_keywords: ['눈을 감고 즐기기', '긴 하루의 마무리로 사용하기', '여행 중 휴식용으로 사용'],
    scene_keywords: ['촛불이 은은한 방에서', '기차 여행 중 창밖을 보며', '하루를 마무리하는 밤'],
    expression_keywords: ['작은 배려로 표현하기', '편안함으로 기억에 남기기'],
    recommended_relations: ['친구', '부모님', '연인', '동료'],
    recommended_occasions: ['생일', '감사', '응원', '스트레스 해소'],
    mood_summary:
      '하루의 피로를 따뜻하게 녹여줄 수 있는 이 선물은 사랑하는 사람의 깊은 휴식을 위한 최고의 선택이에요.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '비타그램 손목 손마사지기 무선 온열 발목 공기압 안마기',
    url: 'https://brand.naver.com/vitagram/products/8670137939',
    image_url:
      'https://shop-phinf.pstatic.net/20230607_240/16861157326095wURO_JPEG/5380760494973252_1463432895.jpg?type=o1000',
    category: ['건강', '리빙/라이프스타일'],
    emotion_keywords: ['편안함', '휴식', '안정', '따뜻함'],
    action_keywords: ['피로 회복', '혼자만의 시간 가진 후', '따뜻함 전하기'],
    scene_keywords: ['저녁에 소파에 앉아', '긴 하루를 마치고 침대에서'],
    expression_keywords: ['작은 배려로 표현', '건강을 챙기는 선물'],
    recommended_relations: ['부모님', '동료', '연인'],
    recommended_occasions: ['감사', '응원', '생일'],
    mood_summary:
      '하루의 피로를 따뜻한 공기압으로 풀어주는 섬세한 선물입니다. 소중한 이에게 편안한 휴식을 선사하세요.',
    target_age: ['30대', '40대', '50대'],
    price: '7-9만원대',
    target_gender: '성별 무관',
  },
  {
    name: '루오딘 저주파 온열 EMS 목 마사지기 승모근 안마기 ML-00401',
    url: 'https://smartstore.naver.com/awesomelyy/products/8180438776',
    image_url:
      'https://shop-phinf.pstatic.net/20250116_170/1737014042387bK1Tn_JPEG/23870895493792598_606584436.jpg?type=o1000',
    category: ['건강', '리빙/라이프스타일'],
    emotion_keywords: ['편안함', '안도감', '휴식', '회복', '따뜻함'],
    action_keywords: ['말 없이 건네기', '하루의 끝에서 사용하기'],
    scene_keywords: ['피곤한 하루의 저녁', '따뜻한 조명의 거실'],
    expression_keywords: ['편안함으로 감싸기', '조용한 배려로 표현'],
    recommended_relations: ['부모님', '연인', '친구', '동료'],
    recommended_occasions: ['생일', '감사', '응원', '스트레스 해소'],
    mood_summary: '하루의 피로를 씻어내는 따뜻하고 편안한 시간을 선물하고 싶을 때.',
    target_age: ['30대', '40대', '50대', '60대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '뮤란드 C7 맥세이프 5 IN 1 무드등 무선충전기 고속충전기 무선충전 거치대',
    url: 'https://smartstore.naver.com/awesomelyy/products/9347864607',
    image_url:
      'https://shop-phinf.pstatic.net/20231222_200/1703227955077cCbl3_JPEG/104363788893044298_1015532772.jpg?type=o1000',
    category: ['리빙/라이프스타일', '기술/가전'],
    emotion_keywords: ['편안함', '실용적임', '현대적임', '기술적 감성', '안락함'],
    action_keywords: ['침대 옆에 두기', '데스크에서 사용하기', '여러 기기 동시 충전하기'],
    scene_keywords: ['늦은 밤 조용한 방에서', '바쁜 아침 출근 준비 전', '작업실에서 집중할 때'],
    expression_keywords: ['빛과 기술로 감동 전달', '작은 편리함 선사하기'],
    recommended_relations: ['친구', '동료', '연인', '부모님'],
    recommended_occasions: ['생일', '감사', '축하', '이사'],
    mood_summary: '편안한 무드로 일상의 효율을 높이고자 하는 사람에게 이상적인 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '리베르 룸스프레이 포레스트 던 120ML',
    url: 'https://www.liber-seoul.com/product/%EB%A3%B8%EC%8A%A4%ED%94%84%EB%A0%88%EC%9D%B4-%ED%8F%AC%EB%A0%88%EC%8A%A4%ED%8A%B8-%EB%8D%98-120ml/193/category/72/display/1/',
    image_url:
      'https://www.liber-seoul.com/web/product/big/202408/99fb666475d44fe46ba386a76d1fb52c.jpg',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['신선함', '평온함', '자연스러움', '회복'],
    action_keywords: ['방 안에 뿌리기', '선물로 건네기'],
    scene_keywords: ['일과를 마치고 돌아온 저녁', '주말 아침의 느긋함'],
    expression_keywords: ['자연의 향기로 감싸기', '조용한 배려를 전하기'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '감사', '응원'],
    mood_summary: '자연의 신선한 향기로 마음의 평온을 선사하는 순간을 전하세요.',
    target_age: ['20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '리베르 디퓨저 탠저린 블랙 100ML',
    url: 'https://www.liber-seoul.com/product/%EB%94%94%ED%93%A8%EC%A0%80-%ED%83%A0%EC%A0%80%EB%A6%B0-%EB%B8%94%EB%9E%99-100ml/71/category/80/display/1/',
    image_url:
      'https://www.liber-seoul.com/web/product/big/202408/54e87c311e75474f09f2716574d2983a.jpg',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['상쾌함', '기분 전환', '청량함'],
    action_keywords: ['휴식 시간에 사용하기', '선물 포장하여 건네기'],
    scene_keywords: ['따사로운 봄날의 오후', '우울한 날씨를 밝히기'],
    expression_keywords: ['상큼한 기운 전달', '향으로 공간 바꾸기'],
    recommended_relations: ['친구', '동료', '친척'],
    recommended_occasions: ['생일', '감사', '응원'],
    mood_summary: '탠저린 블랙의 상쾌한 향은 사랑하는 이에게 기분 좋은 새로움을 선사합니다.',
    target_age: ['20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '여성',
  },
  {
    name: '비타그램 파워 온열 미니 종아리 발마사지기',
    url: 'https://brand.naver.com/vitagram/products/9627049763',
    image_url:
      'https://shop-phinf.pstatic.net/20250113_31/1736742654840IkLWz_JPEG/63382746331719476_180398219.jpg?type=o1000',
    category: ['건강', '리빙/라이프스타일'],
    emotion_keywords: ['편안함', '휴식', '체력회복', '따스함', '피로해소'],
    action_keywords: ['저녁에 휴식을 취하며 사용하기', '스트레칭 후 마사지하기'],
    scene_keywords: ['따뜻한 겨울 저녁', '피곤한 일과를 마친 후'],
    expression_keywords: ['따뜻한 감성과 함께 전하기', '건강을 생각하며 선물하기'],
    recommended_relations: ['부모님', '연인', '친구', '동료'],
    recommended_occasions: ['생일', '감사', '응원'],
    mood_summary: '하루의 피로를 편안히 풀어줄 수 있는 온열 마사지기로 마음을 전하세요.',
    target_age: ['30대', '40대', '50대', '60대'],
    price: '10만원대',
    target_gender: '여성',
  },
  {
    name: '오아 무드 워머 타이머 무드등 향초 캔들 높이조절',
    url: 'https://brand.naver.com/oastore/products/5855140847',
    image_url:
      'https://shop-phinf.pstatic.net/20240802_51/1722577215156uKlzE_JPEG/39904146693471186_398151278.jpg?type=o1000',
    category: ['리빙/라이프스타일', '뷰티'],
    emotion_keywords: ['포근함', '안정감', '로맨틱', '수수함', '따뜻함'],
    action_keywords: ['저녁 시간 활용하기', '취침 전 분위기 잡기', '휴식시간에 사용하기'],
    scene_keywords: [
      '조용한 방에서 책 읽는 밤',
      '은은한 음악과 함께하는 힐링 타임',
      '스트레스 해소하는 저녁',
    ],
    expression_keywords: ['은은하게 감정을 전하기', '분위기로 마음을 전하기', '잔잔한 감동 주기'],
    recommended_relations: ['부모님', '연인', '친구'],
    recommended_occasions: ['생일', '감사', '축하', '집들이'],
    mood_summary: '편안하고 이완된 분위기를 원하는 이들에게 향과 빛으로 감동을 전해보세요.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '[울랄라 Ullala!] 코이즈 반팔 여성페어 핑크 40수',
    rl: 'http://www.10x10.co.kr/shopping/category_prd.asp?itemid=6329479&gaparam=bestaward_b_10',
    image_url: 'http://webimage.10x10.co.kr/image/basic/632/B006329479-1.jpg',
    category: ['리빙/라이프스타일', '패션'],
    emotion_keywords: ['편안함', '부드러움', '포근함', '사랑스러움', '달콤함'],
    action_keywords: ['편안한 저녁에 입기', '휴일에 여유롭게 즐기기'],
    scene_keywords: ['일요일 아침의 느긋함', '창문을 열어 환기를 시키는 봄날'],
    expression_keywords: ['따뜻한 마음 전하기', '세심한 배려를 보여주기'],
    recommended_relations: ['친구', '연인'],
    recommended_occasions: ['생일', '감사', '축하', '응원'],
    mood_summary:
      '이 반팔은 편안하고 사랑스러운 느낌을 줍니다. 데일리웨어로 매일의 일상에 작은 행복을 더할 수 있는 선물입니다.',
    target_age: ['20대', '30대'],
    price: '7-9만원대',
    target_gender: '여성',
  },
  {
    name: '산리오 무선 헤어고데기',
    url: 'http://www.10x10.co.kr/shopping/category_prd.asp?itemid=5735115&gaparam=bestaward_b_18',
    image_url:
      'https://thumbnail.10x10.co.kr/webimage/image/basic600/573/B005735115-1.jpg?cmd=thumb&w=500&h=500&fit=true&ws=false',
    category: ['뷰티', '여행용품'],
    emotion_keywords: ['귀여움', '편리함', '일상적 즐거움', '자신감', '기발함'],
    action_keywords: ['외출 준비할 때 사용하기', '여행 가방에 넣기'],
    scene_keywords: ['아침 출근 준비 시간', '여행지에서 여유롭게 준비하는 저녁'],
    expression_keywords: ['기분을 가볍게 만들기', '장난기 어린 마음 전달하기'],
    recommended_relations: ['친구', '연인', '자매', '동료'],
    recommended_occasions: ['생일', '축하', '감사', '여행 기념'],
    mood_summary: '귀여움과 실용성을 동시에 추구하는 이를 위한 선물로 일상에 즐거움을 더합니다.',
    target_age: ['10대', '20대', '30대'],
    price: '4-6만원대',
    target_gender: '여성',
  },
  {
    name: '솔루엠 스마트워머 MINI 머그워머 보온컵 무선 충전 2in1',
    url: 'https://brand.naver.com/solumstore/products/11027638546?nl-query=%EC%86%94%EB%A3%A8%EC%97%A0%20%EC%8A%A4%EB%A7%88%ED%8A%B8%EC%9B%8C%EB%A8%B8%20MINI%20%EB%A8%B8%EA%B7%B8%EC%9B%8C%EB%A8%B8%20%EB%B3%B4%EC%98%A8%EC%BB%B5%20%EB%AC%B4%EC%84%A0%20%EC%B6%A9%EC%A0%84%202in1&frm=NVSCPSI&nl-ts-pid=jto9GlqVOswssU8%2B4KGssssstXR-278905&NaPm=ci%3Djto9GlqVOswssU8%2B4KGssssstXR-278905%7Cct%3Dmacqx4nq%7Ctr%3Dnsls%7Csn%3D476102%7Chk%3D0eddbcc22e2bd4590e98f77039e99430fb94315a',
    image_url:
      'https://shop-phinf.pstatic.net/20241030_231/17302497845301xRSo_JPEG/64382568622002661_240095526.jpg?type=o1000',
    category: ['리빙/라이프스타일', '건강'],
    emotion_keywords: ['포근함', '안락함', '편안함'],
    action_keywords: ['차 한 잔과 즐기기', '선물로 건네기'],
    scene_keywords: ['사무실의 조용한 오후', '집에서의 여유로운 아침'],
    expression_keywords: ['따뜻한 마음 전달', '작은 배려 느끼기'],
    recommended_relations: ['동료', '친구', '부모님'],
    recommended_occasions: ['감사', '응원', '겨울 맞이'],
    mood_summary: '차 한 잔의 따뜻함이 필요한 순간에 마음을 녹여줄 배려 깊은 선물',
    target_age: ['20대', '30대', '40대'],
    price: '7-9만원대',
    target_gender: '성별 무관',
  },
  {
    name: '오설록 [보자기] 프리미엄 티 컬렉션 10종 40입',
    url: 'https://www.osulloc.com/kr/ko/shop/item/teashop/21897',
    image_url: 'https://image.osulloc.com/upload/kr/ko/adminImage/VD/BN/20250421094452139OM.png',
    category: ['디저트/카페', '리빙/라이프스타일'],
    emotion_keywords: ['풍성함', '평온함', '고급스러움'],
    action_keywords: ['티타임 갖기', '차와 함께 대화 나누기'],
    scene_keywords: ['따뜻한 오후의 거실', '친구들과의 모임'],
    expression_keywords: ['향기로 기억에 남기기', '평온함 선사하기'],
    recommended_relations: ['부모님', '친구', '상사', '연인'],
    recommended_occasions: ['생일', '감사', '축하', '응원'],
    mood_summary: '따뜻한 차 한 잔으로 마음의 평온을 선사하는 순간을 위한 특별한 선물입니다.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '오설록 와플 티 4종 세트',
    url: 'https://www.osulloc.com/kr/ko/shop/item/teashop/21825',
    image_url: 'https://image.osulloc.com/upload/kr/ko/adminImage/OY/OX/20250507115649219SE.png',
    category: ['디저트/카페', '리빙/라이프스타일'],
    emotion_keywords: ['따뜻함', '달콤함', '편안함', '정겨움'],
    action_keywords: ['차와 함께 즐기기', '여유로운 오후에 꺼내기'],
    scene_keywords: ['포근한 오후 햇살 아래', '책과 함께 하는 시간'],
    expression_keywords: ['달콤한 기운을 전하기', '평범한 날을 특별하게'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['감사', '축하', '응원'],
    mood_summary: '달콤한 순간을 공유하며 따뜻한 마음을 전할 수 있는 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '오설록 유리티팟 표일배',
    url: 'https://www.osulloc.com/kr/ko/shop/item/themashop/21832',
    image_url: 'https://image.osulloc.com/upload/kr/ko/adminImage/TC/DS/20250325190853773BU.webp',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['편안함', '우아함', '여유', '정취', '섬세함'],
    action_keywords: ['차 한 잔을 우려내기', '여유로운 오후 보내기'],
    scene_keywords: ['햇빛이 드는 창가', '잔잔한 음악이 흐르는 거실'],
    expression_keywords: ['정성을 담아', '차분함을 선물'],
    recommended_relations: ['부모님', '친구', '동료', '연인'],
    recommended_occasions: ['생일', '감사', '축하', '응원'],
    mood_summary: '정성을 담아 선물하는 순간의 깊이를 더해주는 티팟.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '오제티 카네이션 캔들 (돔 사이즈)',
    url: 'https://smartstore.naver.com/ohzeti/products/8432454680',
    image_url:
      'https://shop-phinf.pstatic.net/20230420_150/1681992055278d9M7v_JPEG/32343456243939041_629482296.jpg?type=o1000',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['감사', '따뜻함', '정성'],
    action_keywords: ['부드럽게 불을 밝히기', '향기롭게 분위기 전환'],
    scene_keywords: ['햇살 드는 오후 거실', '잔잔한 음악과 함께 하는 저녁'],
    expression_keywords: ['정성스럽게 포장하여 드리기', '향기로 기억에 남기기'],
    recommended_relations: ['부모님', '선생님', '친구'],
    recommended_occasions: ['감사', '축하', '기념일'],
    mood_summary: '따뜻한 마음과 감사의 정서를 담아 특별한 사람에게 전하는 선물입니다.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '트윈 클로버즈 캔들 / 딥그린 집들이선물 인테리어',
    url: 'https://smartstore.naver.com/ohzeti/products/11457552330',
    image_url:
      'https://shop-phinf.pstatic.net/20250211_204/1739247334131v57iQ_JPEG/498644240863106_878419527.jpg?type=o1000',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['평화로움', '안정감', '신선함', '자연스러움'],
    action_keywords: ['이사 축하하며 건네기', '집들이에서 중앙에 놓기'],
    scene_keywords: ['조용한 저녁 거실', '산들바람이 부는 창가'],
    expression_keywords: ['촛불로 마음을 전하기', '향기로 공간을 채우기'],
    recommended_relations: ['친구', '동료'],
    recommended_occasions: ['집들이', '이사 축하', '어버이날'],
    mood_summary:
      '딥그린의 촛불이 은은하게 퍼져나가는 공간에서의 평온함과 자연의 신선함을 동시에 느낄 수 있는 선물이에요.',
    target_age: ['20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '성별 무관',
  },
  {
    name: '오제티 빅 캐니스터 소원 캔들 (키링+캔들라이터 증정)',
    url: 'https://smartstore.naver.com/ohzeti/products/11457466530',
    image_url:
      'https://shop-phinf.pstatic.net/20250211_143/1739246034606WWPLf_JPEG/499389718440825_1093706350.jpg?type=o1000',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['따뜻함', '편안함', '희망', '명상', '안정'],
    action_keywords: ['소원을 빌며 불을 켜기', '저녁에 휴식을 취하기'],
    scene_keywords: ['조용한 밤의 거실', '침실의 은은한 조명 아래'],
    expression_keywords: ['소망을 담아 전하기', '은은한 향기로 마음을 전하기'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '응원', '축하', '집들이'],
    mood_summary: '소원을 담은 촛불로 일상에 작은 마법을 더해주는 순간을 만들어 보세요.',
    target_age: ['20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '콜린스 인센스 기프트 세트',
    url: 'https://www.collinslife.co/product/collins-incense-giftset',
    image_url: 'https://fly.gitt.co/collins/wp-content/uploads/2021/10/insense_-set02.png',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['평온함', '안정', '편안함', '명상', '진정'],
    action_keywords: ['명상할 때 사용하기', '집중이 필요할 때 점화하기'],
    scene_keywords: ['조용한 아침 햇살 속', '저녁의 은은한 조명 아래', '산책 후 따뜻한 집에서'],
    expression_keywords: ['향기로 기억에 남기기', '공간을 아름답게 표현하기'],
    recommended_relations: ['친구', '부모님', '연인', '자신'],
    recommended_occasions: ['생일', '감사', '축하', '응원'],
    mood_summary: '마음의 평화를 찾고 싶은 당신에게, 은은한 향기로 공간을 감싸주는 선물',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: 'TWG 그랜드 티 테이스터 콜렉션',
    url: 'https://twgkorea.com/product/%EA%B7%B8%EB%9E%9C%EB%93%9C-%ED%8B%B0-%ED%85%8C%EC%9D%B4%EC%8A%A4%ED%84%B0-%EC%BD%9C%EB%A0%89%EC%85%98/181/category/23/display/1/',
    image_url: 'https://twgkorea.com/web/product/big/202105/565b27321dbf2385e33198cd945f75ea.jpg',
    category: ['리빙/라이프스타일', '디저트/카페'],
    emotion_keywords: ['우아함', '편안함', '섬세함', '강한 향기', '특별함'],
    action_keywords: ['저녁 티타임에 활용', '조용한 순간을 즐기기'],
    scene_keywords: ['해 질 녘 테라스에서', '평온한 오후 거실에서'],
    expression_keywords: ['향기로 기억에 남기기', '작은 배려로 표현'],
    recommended_relations: ['친구', '연인', '부모님', '동료'],
    recommended_occasions: ['생일', '감사', '축하', '응원'],
    mood_summary: '하루의 스트레스를 녹이고 싶은 그들에게, 잔잔한 차 한잔의 선택을 선사하세요.',
    target_age: ['20대', '30대', '40대'],
    price: '7-9만원대',
    target_gender: '성별 무관',
  },
  {
    name: '원목 플랜테리어 식물 LED 무선 무드등 집들이선물 네추럴베이지 이오난사기본',
    url: 'https://brand.naver.com/modernpoint/products/6161078427?n_media=27758&n_query=%EB%AA%A8%EB%8D%98%ED%8F%AC%EC%9D%B8%ED%8A%B8LED%EC%8B%9D%EB%AC%BC%EB%AC%B4%EB%93%9C%EB%93%B1&n_rank=1&n_ad_group=grp-a001-01-000000028691611&n_ad=nad-a001-01-000000280209097&n_campaign_type=1&n_ad_group_type=1&n_match=2&NaPm=ct%3Dma8700x1%7Cci%3DER37321dea%2D2819%2D11f0%2Da248%2D562c62531e3c%7Ctr%3Dsa%7Chk%3D85bf42544622023faafa2e0d4110fe51c8c88033%7Cnacn%3DmYNWBkws3jyd',
    image_url:
      'https://shop-phinf.pstatic.net/20250213_295/1739421803694BIfBV_JPEG/15386477842923391_832965451.jpg?type=o1000',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['편안함', '힐링', '자연스러움'],
    action_keywords: ['새로운 공간에 배치하기', '휴식 시간 사용'],
    scene_keywords: ['평화로운 저녁', '식물 가득한 거실'],
    expression_keywords: ['자연의 소박함 전달', '휴식의 중요성 강조'],
    recommended_relations: ['친구', '동료', '부모님'],
    recommended_occasions: ['집들이', '감사', '축하'],
    mood_summary: '자연과 함께하는 휴식의 순간을 선물하며 새 공간의 따뜻한 분위기를 더해줍니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '그랑핸드 마린 오키드 멀티퍼퓸',
    url: 'https://granhand.com/perfume/?idx=28',
    image_url: 'https://cdn.imweb.me/thumbnail/20210526/bfe6dda826ea8.jpg',
    category: ['향수', '라이프스타일'],
    emotion_keywords: ['청량함', '섬세함', '맑고 깨끗함'],
    action_keywords: ['공간에 향기 입히기', '리넨에 분사하기', '일상 속 기분전환'],
    scene_keywords: ['햇살 가득한 아침', '깨끗하게 정돈된 방 안', '여름 바람이 스치는 오후'],
    expression_keywords: ['바다 향기를 닮은 상쾌함', '섬세하게 퍼지는 오키드 향기'],
    recommended_relations: ['친구', '연인'],
    recommended_occasions: ['집들이', '생일', '기념일', '응원'],
    mood_summary:
      '맑고 투명한 마린 향기에 은은한 오키드가 더해져, 공간과 일상에 청량한 분위기를 선사하는 멀티퍼퓸입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '후후루 플뢰르 도브 - 드라이 프리저브드 플라워 하바리움 무드등',
    url: 'https://smartstore.naver.com/huhuru/products/10219665266?nt_source=kakao&nt_medium=biz&nt_detail=flower220429',
    image_url:
      'https://shop-phinf.pstatic.net/20250415_209/17447085015223Ixfl_JPEG/30269366360006222_443246633.jpg?type=o1000',
    category: ['인테리어 소품'],
    emotion_keywords: ['감성적', '로맨틱', '힐링'],
    action_keywords: ['감성적인 선물하기', '특별한 날 분위기 연출'],
    scene_keywords: ['감성적인 조명의 따뜻한 빛', '집들이 선물로 적합'],
    expression_keywords: ['감성적인 순간의 특별 연출', '은은한 감성 전달'],
    recommended_relations: ['가장 소중한 사람', '소중한 친구'],
    recommended_occasions: ['생일', '기념일', '집들이'],
    mood_summary:
      '감성적이고 은은한 분위기를 전달하여, 특별한 날을 더욱 의미 있게 만들어주는 로맨틱한 선물입니다.',
    target_age: ['20대', '30대'],
    price: '7-9만원대',
    target_gender: '여성',
  },
  {
    name: '코닥 미니샷2 ERA 즉석 카메라 + 카트리지 68매 번들',
    url: 'https://kodakphotoprinter.co.kr/product/%EC%BD%94%EB%8B%A5-%EB%AF%B8%EB%8B%88%EC%83%B72-era-%EC%A6%89%EC%84%9D-%EC%B9%B4%EB%A9%94%EB%9D%BC%EC%B9%B4%ED%8A%B8%EB%A6%AC%EC%A7%80-68%EB%A7%A4-%EB%B2%88%EB%93%A4/66/category/107/display/1/',
    image_url:
      'https://kodakphotoprinter.co.kr/web/product/big/202501/4191cd12cc522e2d2c2991b1d486b343.png',
    category: ['디지털', '가전'],
    emotion_keywords: ['레트로', '감성', '특별함'],
    action_keywords: ['소중한 추억 남기기', '감성 사진 찍기'],
    scene_keywords: ['여행 중 특별한 순간', '소중한 기억을 담는 순간'],
    expression_keywords: ['추억을 오래 간직하기', '감성적인 사진 선물'],
    recommended_relations: ['가장 소중한 사람', '친한 친구'],
    recommended_occasions: ['여행 전', '생일'],
    mood_summary: '레트로 감성과 함께 소중한 추억을 오래 간직할 수 있는 특별한 순간을 선물합니다.',
    target_age: ['10대', '20대', '30대'],
    price: '20만원대',
    target_gender: '성별 무관',
  },
  {
    name: '빛과 실 - 한강',
    url: 'https://www.yes24.com/Product/Goods/145569016',
    image_url: 'https://image.yes24.com/goods/145569016/XL',
    category: ['도서', '에세이'],
    emotion_keywords: ['감성적', '예술적', '철학적'],
    action_keywords: ['깊은 위로의 선물', '조용한 감성 나누기'],
    scene_keywords: ['조용한 저녁의 독서 시간', '위로가 필요한 순간'],
    expression_keywords: ['진심 어린 위로', '감성과 철학의 깊이 있는 전달'],
    recommended_relations: ['가장 소중한 사람', '조용한 친구'],
    recommended_occasions: ['생일', '기념일', '위로가 필요한 날'],
    mood_summary: '깊이 있는 위로와 감성을 전하며, 진심 어린 마음을 담아낸 선물입니다.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '성별 무관',
  },
  {
    name: '[휘낭시에 패키지] 디저트 선물 센스있는 고급 답례품',
    url: 'https://smartstore.naver.com/patisseriearmoni/products/8822368104',
    image_url:
      'https://shop-phinf.pstatic.net/20230701_288/1688190430706JQC3f_JPEG/3677718940364646_674348238.jpg?type=o1000',
    category: ['디저트', '식품'],
    emotion_keywords: ['고급스러움', '달콤함', '세련됨'],
    action_keywords: ['정성 가득한 답례품', '부담 없이 기분 좋은 선물'],
    scene_keywords: ['감사 인사의 자리에서', '답례품으로 적합'],
    expression_keywords: ['센스 있는 달콤한 선물', '부담 없는 정성 전하기'],
    recommended_relations: ['비즈니스 관계', '가벼운 인사'],
    recommended_occasions: ['감사 인사', '답례품'],
    mood_summary: '센스 있는 포장과 고급스러운 디저트로, 부담 없이 기분 좋은 정성을 전합니다.',
    target_age: ['30대', '40대', '50대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '센슈얼 누드 글로스 5g',
    url: 'https://www.amoremall.com/kr/ko/product/detail?onlineProdSn=31573&onlineProdCode=111070000890',
    image_url:
      'https://images-kr.amoremall.com/products/111070000890/111070000890_01.png?1725234770311&resize=1100:1100&shrink=1100:1100',
    category: ['화장품', '뷰티'],
    emotion_keywords: ['세련됨', '감각적', '여성스러움'],
    action_keywords: ['일상 속 작은 기쁨 선물하기', '데일리템 선물하기'],
    scene_keywords: ['연인과의 데이트 전', '일상 속 여성스러움'],
    expression_keywords: ['작은 세련된 기쁨', '일상 속 특별함'],
    recommended_relations: ['가장 소중한 사람', '연인'],
    recommended_occasions: ['생일', '기념일'],
    mood_summary: '세련된 감각을 일상 속에서 전하며, 작은 기쁨을 선물하는 아이템입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '여성',
  },
  {
    name: '엘 오브라헤: 카스티요 (EL OBRAJE: CASTILLO)',
    url: 'https://beanbrothers.co.kr/goods/goods_view.php?goodsNo=1000000563',
    image_url:
      'https://godomall.speedycdn.net/2b2d2b9256ca4144b5bd52e460a0a675/goods/1000000563/image/detail/1000000563_detail_071.png',
    category: ['식품', '커피'],
    emotion_keywords: ['스페셜티', '향미 중심', '고급스러움'],
    action_keywords: ['특별한 커피 선물', '일상의 향기로운 여유'],
    scene_keywords: ['커피 애호가에게 적합', '향기로운 여유의 시간'],
    expression_keywords: ['섬세한 취향', '고급스러운 스페셜티 선물'],
    recommended_relations: ['커피 애호가', '취향을 공유하는 지인'],
    recommended_occasions: ['생일', '감사 인사'],
    mood_summary:
      '스페셜티 커피로 섬세한 취향을 고려한 특별함과 일상을 위한 향기로운 여유를 선물합니다.',
    target_age: ['20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '성별 무관',
  },
  {
    name: '[고급 보자기 포장] 연과 선물 세트 12개입',
    url: 'https://smartstore.naver.com/projectharu/products/5112651999',
    image_url:
      'https://shop-phinf.pstatic.net/20220830_182/1661811212851gfHxq_JPEG/62947111416227769_334438772.jpg?type=o1000',
    category: ['디저트', '전통 식품'],
    emotion_keywords: ['전통', '고급스러움', '정성'],
    action_keywords: ['전통적인 감사 표현', '고급스러운 마음 전달'],
    scene_keywords: ['명절의 정성스러운 선물', '고급 보자기 포장의 특별함'],
    expression_keywords: ['전통의 고급스러움', '정성 가득한 마음'],
    recommended_relations: ['부모님', '어르신'],
    recommended_occasions: ['명절', '감사 인사'],
    mood_summary: '전통과 고급스러움을 담아, 마음을 담은 정성스러운 감사의 선물입니다.',
    target_age: ['30대', '40대', '50대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '퍼퓸 캔들 펌키니 (Perfume Candle PUMKINI)',
    url: 'https://www.tamburins.com/kr/item/1697693723/',
    image_url:
      'https://web-resource.tamburins.com/catalog/product/1697693723/4a45ec9f-3e91-4aec-8b44-a4a10e22e242/Thumbnail_PerfumeCandle_200g_pumkini.jpg',
    category: ['홈 프래그런스', '캔들'],
    emotion_keywords: ['감성적', '고급스러움', '트렌디'],
    action_keywords: ['무드 있는 공간 연출', '특별한 향 선물'],
    scene_keywords: ['집들이의 트렌디한 선물', '감성적인 공간의 향'],
    expression_keywords: ['감각적 무드 선물', '공간의 특별한 향'],
    recommended_relations: ['친구', '연인'],
    recommended_occasions: ['집들이', '기념일'],
    mood_summary: '감각적인 무드와 향으로 공간에 특별함과 감성을 더해주는 선물입니다.',
    target_age: ['20대', '30대'],
    price: '7-9만원대',
    target_gender: '여성',
  },
  {
    name: '휩드 팩클렌저 단지',
    url: 'https://whipped.co.kr/product/%ED%9C%A9%EB%93%9C-%ED%8C%A9%ED%81%B4%EB%A0%8C%EC%A0%80-%EB%8B%A8%EC%A7%80-2%EC%A2%85-%EA%B3%A8%EB%9D%BC%EB%8B%98%EA%B8%B0/223/category/48/display/1/',
    image_url: 'https://whipped.co.kr/web/product/big/202408/3455e3cdb83652dbcae99926034bca2d.jpg',
    category: ['화장품', '스킨케어'],
    emotion_keywords: ['비건', '감성적', '보습'],
    action_keywords: ['섬세한 피부 배려', '환경 고려한 선물'],
    scene_keywords: ['민감성 피부를 가진 친구에게', '환경을 생각하는 사람에게'],
    expression_keywords: ['피부 고민 케어', '비건 감성의 배려'],
    recommended_relations: ['가장 소중한 사람', '친구'],
    recommended_occasions: ['생일', '감사 인사'],
    mood_summary: '비건 감성을 담아 피부를 섬세하게 배려하는 특별한 스킨케어 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '여성',
  },
  {
    name: '조말론 사이프러스 앤 그레이프바인 익스폴리에이팅 샤워 젤',
    url: 'https://www.jomalone.co.kr/product/25956/79593/cypress-grapevine-exfoliating-shower-gel-200ml',
    image_url:
      'https://www.jomalone.co.kr/media/export/cms/products/1000x1000/jo_sku_LCWC01_1000x1000_0.png',
    category: ['바디케어', '샤워 젤'],
    emotion_keywords: ['고급스러움', '세련됨', '프리미엄'],
    action_keywords: ['세련된 향 선물', '특별한 그루밍 선물'],
    scene_keywords: ['남자친구를 위한 선물', '취향 있는 남성을 위한'],
    expression_keywords: ['향과 관리의 특별함', '고급 샤워 젤 선물'],
    recommended_relations: ['연인', '친구'],
    recommended_occasions: ['생일', '기념일'],
    mood_summary:
      '고급스러운 그루밍 아이템으로, 세련된 향과 관리를 선물하는 프리미엄 샤워 젤입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '7-9만원대',
    target_gender: '남성',
  },
  {
    name: '해늘 티타임세트 3종 선물세트',
    url: 'https://eleganttable.co.kr/product/detail.html?product_no=652&cate_no=1&display_group=2',
    image_url:
      'https://eleganttable.co.kr/web/product/big/202502/e2fcc4d9306fd85ad4c268c83da90aea.jpg',
    category: ['키친', '테이블웨어'],
    emotion_keywords: ['감성적', '따뜻함', '실용적'],
    action_keywords: ['따뜻한 일상 선물', '신혼집에 감각적인 선택'],
    scene_keywords: ['신혼 부부에게 적합', '집들이 선물로 추천'],
    expression_keywords: ['감성적인 테이블웨어', '따뜻한 무드 전달'],
    recommended_relations: ['신혼부부', '친한 친구'],
    recommended_occasions: ['집들이', '신혼 선물'],
    mood_summary: '따뜻한 감성의 테이블웨어로, 실용적이면서도 감각적인 일상을 선물합니다.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '올리 2구 팝업 토스트기 스텐 토스터기',
    url: 'https://brand.naver.com/olly/products/5210850812',
    image_url:
      'https://shop-phinf.pstatic.net/20250115_225/1736906340348wacqD_JPEG/71039205490862573_15603071.jpg?type=o1000',
    category: ['가전', '주방가전'],
    emotion_keywords: ['심플', '미니멀', '실용적'],
    action_keywords: ['아침을 따뜻하게 시작', '실용적인 주방 가전 선물'],
    scene_keywords: ['자취 시작한 친구에게', '신혼 부부를 위한'],
    expression_keywords: ['아침 루틴의 심플함', '깔끔한 주방 가전'],
    recommended_relations: ['친구', '신혼부부'],
    recommended_occasions: ['자취 시작', '생일'],
    mood_summary:
      '아침을 더욱 따뜻하게 시작할 수 있는, 실용적이면서 센스 있는 주방 가전 선물입니다.',
    target_age: ['20대', '30대'],
    price: '4-6만원대',
    target_gender: '여성',
  },
  {
    name: 'DYVLINGE 뒤블링에 회전 이지체어 - 셸링에 그린',
    url: 'https://www.ikea.com/kr/ko/p/dyvlinge-swivel-easy-chair-kelinge-green-70570836/',
    image_url:
      'https://www.ikea.com/kr/ko/images/products/dyvlinge-swivel-easy-chair-kelinge-green__1205904_pe907276_s5.jpg?f=l',
    category: ['가구', '의자'],
    emotion_keywords: ['감성적', '모던', '편안함'],
    action_keywords: ['편안한 휴식 선물', '인테리어 포인트 전달'],
    scene_keywords: ['신혼의 편안한 공간', '인테리어를 완성하는 의자'],
    expression_keywords: ['편안함과 모던함의 조화', '감성 있는 인테리어'],
    recommended_relations: ['가장 소중한 사람', '연인'],
    recommended_occasions: ['신혼 선물', '이사 선물'],
    mood_summary:
      '편안한 휴식을 제공하며, 감성 있는 인테리어를 완성할 수 있는 회전 이지체어입니다.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '20만원대',
    target_gender: '성별 무관',
  },
  {
    name: '제주애기모람 호수 테라리움 만들기 DIY 키트',
    url: 'https://smartstore.naver.com/dugiterra/products/11679676277',
    image_url:
      'https://shop-phinf.pstatic.net/20250405_204/1743789968194uB5iX_JPEG/2168064381235293_1722447571.jpg?type=o1000',
    category: ['DIY', '인테리어 소품'],
    emotion_keywords: ['힐링', '감성', '자연'],
    action_keywords: ['직접 만드는 재미 선물하기', '자연과 감성의 여유 제공'],
    scene_keywords: ['히르 만한 나만의 공간', '자연적인 힐링의 순간'],
    expression_keywords: ['DIY의 감성적인 여유', '자연 그대로의 감성 전달'],
    recommended_relations: ['감성을 공유하는 친구', '힐링이 필요한 사람'],
    recommended_occasions: ['집들이', '생일'],
    mood_summary: '직접 만드는 테라리움으로 자연과 감성의 여유를 선물하는 특별한 DIY 키트입니다.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '여성',
  },
  {
    name: '별자리 지도 포스터',
    url: 'https://posterstore.kr/p/EC-95-84-ED-8A-B8-EC-9B-8C-ED-81-AC--ED-8F-AC-EC-8A-A4-ED-84-B0/EB-8F-99-EA-B8-B0-EB-B6-80-EC-97-AC--EB-AA-85-EC-83-81/%EB%B3%84%EC%9E%90%EB%A6%AC-%EC%A7%80%EB%8F%84-%ED%8F%AC%EC%8A%A4%ED%84%B0/',
    image_url: 'https://img.posterstore.com/zoom/ps52235.jpg',
    category: ['인테리어 소품', '포스터'],
    emotion_keywords: ['감성적', '로맨틱', '맞춤형'],
    action_keywords: ['특별한 기억 선물하기', '의미 있는 날 감성 기록'],
    scene_keywords: ['로맨틱한 인테리어 포인트', '특별한 날의 소중함'],
    expression_keywords: ['별자리의 감성', '기념일의 특별함 전달'],
    recommended_relations: ['연인', '친한 친구'],
    recommended_occasions: ['생일', '기념일'],
    mood_summary:
      '별자리와 함께 특별한 순간을 감성적으로 기록하며 기억에 남기는 맞춤형 포스터입니다.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '마샬 윌렌 Ⅱ (Marshall Willen Ⅱ)',
    url: 'https://brand.naver.com/marshall/products/10907829258',
    image_url:
      'https://shop-phinf.pstatic.net/20240923_284/1727055795503cpPcU_PNG/61188648080205852_534295387.png?type=o1000',
    category: ['디지털', '블루투스 스피커'],
    emotion_keywords: ['프리미엄', '레트로', '강력한 사운드'],
    action_keywords: ['감성적 사운드 선물하기', '휴대성과 디자인 모두 전하기'],
    scene_keywords: ['휴대와 야외 활동 적합', '강력한 사운드의 감동'],
    expression_keywords: ['음악의 감성 제공', '프리미엄 사운드와 디자인'],
    recommended_relations: ['연인', '친구'],
    recommended_occasions: ['생일', '기념일'],
    mood_summary:
      '감성적이면서 강력한 사운드를 선사하며, 프리미엄 디자인과 사운드를 모두 갖춘 스피커입니다.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '10만원대',
    target_gender: '성별 무관',
  },
  {
    name: '오쏘몰 이뮨 멀티비타민 30일분',
    url: 'https://brand.naver.com/dapharm/products/5684175077',
    image_url:
      'https://shop-phinf.pstatic.net/20250430_201/1745995898638TA9Rn_JPEG/80128839755580110_1885612834.jpg?type=o1000',
    category: ['건강기능식품', '비타민'],
    emotion_keywords: ['프리미엄', '면역력 강화', '진심'],
    action_keywords: ['건강 챙기기', '진심 전하는 건강 선물'],
    scene_keywords: ['환절기 선물로 좋음', '건강을 위한 실속 구성'],
    expression_keywords: ['진심이 느껴지는 영양 선물', '면역력 강화를 위한 비타민'],
    recommended_relations: ['부모님', '연인'],
    recommended_occasions: ['생일', '환절기'],
    mood_summary:
      '건강을 챙기며 진심을 전달하여, 지친 일상에 활력을 주는 프리미엄 비타민 선물입니다.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '10만원대',
    target_gender: '성별 무관',
  },
  {
    name: '고려은단 메가도스C 3000 영국산 비타민C 100포',
    url: 'https://brand.naver.com/koreaeundanhc/products/5220755158',
    image_url:
      'https://shop-phinf.pstatic.net/20230405_170/16806799581861uGJn_JPEG/81815741902594620_1099000415.jpg?type=o1000',
    category: ['건강기능식품', '비타민'],
    emotion_keywords: ['실속형', '간편함', '에너지 충전'],
    action_keywords: ['간편하게 건강 챙기기', '실속 있는 건강 선물'],
    scene_keywords: ['환절기의 감기 예방', '직장인 건강 챙기기'],
    expression_keywords: ['일일 비타민C 섭취', '실속 있는 건강 선물'],
    recommended_relations: ['부모님', '친구', '동료'],
    recommended_occasions: ['환절기', '감기 예방'],
    mood_summary:
      '간편하게 건강을 챙길 수 있는 실속 있는 건강 선물로, 일일 비타진의 기초가 되어줍니다.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '해가 지는 곳으로 (사인본)',
    url: 'https://product.kyobobook.co.kr/detail/S000000620599',
    image_url: 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937473166.jpg',
    category: ['도서', '소설'],
    emotion_keywords: ['감성적', '로맨스', '디스토피아'],
    action_keywords: ['깊은 여운 전하기', '사랑과 희망의 서사 전달'],
    scene_keywords: ['기억에 남을 만한 책 선물', '디스토피아 속 사랑 이야기'],
    expression_keywords: ['사인본 한정판의 특별함', '로맨스와 생존의 서사 전달'],
    recommended_relations: ['연인', '친구'],
    recommended_occasions: ['생일', '감성 선물'],
    mood_summary:
      '디스토피아 속에서도 피어나는 사랑과 희망의 서사를 전하여, 감성을 공유하는 이에게 깊은 여운을 주는 특별한 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '여성',
  },
  {
    name: '휴그 붕어빵 워머 보조배터리',
    url: 'https://huug.shop/shop/?idx=70',
    image_url: 'https://cdn.imweb.me/thumbnail/20241104/08fddd862f49a.jpg',
    category: ['디지털', '보조배터리'],
    emotion_keywords: ['따뜻함', '귀여움', '감성적'],
    action_keywords: ['추운 날씨에 따뜻함 선물', '감성적인 디자인의 실용성 제공'],
    scene_keywords: ['겨울철 감성적인 보조배터리', '따뜻한 손난로 기능'],
    expression_keywords: ['감성과 실용성 겸비', '귀여운 디자인의 젊은 감각'],
    recommended_relations: ['친한 친구', '연인'],
    recommended_occasions: ['겨울철', '생일'],
    mood_summary:
      '추운 날씨에 따뜻함과 실용성을 동시에 제공하여, 감성을 전하는 귀여운 디자인의 보조배터리입니다.',
    target_age: ['10대', '20대', '30대'],
    price: '2만원대',
    target_gender: '여성',
  },
  {
    name: '휴그 Y2K 캠코더',
    url: 'https://huug.shop/shop/?idx=40',
    image_url: 'https://cdn.imweb.me/thumbnail/20241211/6894a6bfa17de.jpg',
    category: ['디지털', '캠코더'],
    emotion_keywords: ['레트로', 'Y2K 감성', '가벼움'],
    action_keywords: ['특별한 추억 선물', '감성을 담아 기억 남기기'],
    scene_keywords: ['여행 전 특별한 기념 촬영', '감성적 영상 기록'],
    expression_keywords: ['레트로 감성의 추억 기록', 'HD 촬영의 특별함'],
    recommended_relations: ['연인', '친한 친구'],
    recommended_occasions: ['생일', '기념일'],
    mood_summary: '레트로 감성의 미니 캠코더로, 특별한 추억을 감성적으로 담아내는 선물입니다.',
    target_age: ['10대', '20대', '30대'],
    price: '3만원대',
    target_gender: '여성',
  },
  {
    name: '오니프 사색의 조각 책꽂이',
    url: 'https://onif.kr/product/%EC%82%AC%EC%83%89%EC%9D%98-%EC%A1%B0%EA%B0%81-%EC%B1%85%EA%BD%82%EC%9D%B4/297/category/1/display/2/',
    image_url: 'https://onif.kr/web/product/big/202410/20e7abdfb3b6e351dc2118225b3e50d8.jpg',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['평온함', '고요함', '정적'],
    action_keywords: ['서재 선반에 정리', '편안한 독서 공간 연출'],
    scene_keywords: ['비 오는 날 오후', '조용한 서재의 창가'],
    expression_keywords: ['미묘한 감정 전달', '세심함을 드러내기'],
    recommended_relations: ['친구', '동료', '연인'],
    recommended_occasions: ['집들이', '졸업', '이사 축하'],
    mood_summary: '사색의 순간을 즐기는 이를 위한 고요하고 세련된 공간을 만들어주는 선물.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '여성',
  },
  {
    name: '러쉬 슬리피 버블바',
    url: 'https://www.lush.co.kr/m/products/view/1000001226?dc=standard',
    image_url: 'https://www.lush.co.kr/upload/heroImage/20240911105047L.jpg',
    category: ['뷰티', '리빙/라이프스타일'],
    emotion_keywords: ['편안함', '안정감', '행복', '달콤함', '자연스러움'],
    action_keywords: ['기분 전환용', '스트레스 해소', '자기 전 입욕'],
    scene_keywords: ['긴 하루의 끝', '호젓한 밤', '편안한 욕실'],
    expression_keywords: ['하루의 피로를 녹이는', '작은 사치로 희망찬 새벽 맞이'],
    recommended_relations: ['친구', '연인', '부모님', '동료'],
    recommended_occasions: ['생일', '응원', '감사', '축하'],
    mood_summary: '긴 하루를 마무리할 때, 부드럽고 달콤한 향기로 마음의 휴식을 선사하는 선물.',
    target_age: ['20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '성별 무관',
  },
  {
    name: '사파리 만년필 차콜블랙 EF',
    url: 'https://lamyshop.kr/web/product/big/202408/f779033b907eaffaa390b118154ba957.png',
    image_url: 'https://www.lush.co.kr/upload/item/1000001226/20240911105047L.png',
    category: ['리빙/라이프스타일', '문구'],
    emotion_keywords: ['정교함', '고요함', '우아함'],
    action_keywords: ['정성 들여 글씨 쓰기', '편지 적기'],
    scene_keywords: ['조용한 카페에서', '책상에 앉아'],
    expression_keywords: ['정성을 표현하기', '개성을 드러내기'],
    recommended_relations: ['친구', '동료', '상사', '연인'],
    recommended_occasions: ['생일', '감사', '축하'],
    mood_summary: '고요한 순간들의 특별함을 더해주는 세련되고 정교한 만년필입니다.',
    target_age: ['20대', '30대', '40대', '50대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '한스갤러리 피크닉 매트 감성 프렌치 방수 돗자리 120x120',
    url: 'https://brand.naver.com/hansgallery/products/4353775384',
    image_url:
      'https://shop-phinf.pstatic.net/20240930_116/1727662329823Vgi0f_JPEG/48287258823875189_1694739649.jpg?type=o1000',
    category: ['리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['자유로움', '편안함', '즐거움', '유쾌함', '상쾌함'],
    action_keywords: ['함께 앉아서 즐기기', '자연 속에서 펼치기'],
    scene_keywords: [
      '햇살 가득한 봄날 공원에서',
      '바람이 부는 해변가에서',
      '도시 속 작은 녹지에서',
    ],
    expression_keywords: ['자연을 만끽하게 하기', '작은 휴식 선물하기'],
    recommended_relations: ['친구', '연인', '부모님'],
    recommended_occasions: ['소풍', '기념일', '여행'],
    mood_summary: '자연 속에서 행복한 순간을 만들고 싶은 사람에게 어울리는 감성 피크닉 매트입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '여성',
  },
  {
    name: '로지텍코리아 로지텍 LIFT 버티컬 무선 마우스 그래파이트',
    url: 'https://brand.naver.com/logitech/products/6542209601',
    image_url:
      'https://shop-phinf.pstatic.net/20250217_88/1739757115798vVssJ_JPEG/16159569932043495_487560181.jpg?type=o1000',
    category: ['리빙/라이프스타일', '테크'],
    emotion_keywords: ['섬세함', '편안함', '모던함', '차분함', '따뜻함'],
    action_keywords: ['직장에서 사용할 때', '홈오피스를 꾸밀 때', '편안한 작업 환경 만들기'],
    scene_keywords: ['창문 옆 작은 사무실', '햇살 드는 작업 공간'],
    expression_keywords: ['건강을 챙기며 배려하기', '작은 디테일로 마음 표현하기'],
    recommended_relations: ['동료', '친구', '상사'],
    recommended_occasions: ['감사', '응원', '취업 축하'],
    mood_summary: '세심함과 편안함을 함께 전하는, 손목에 부담을 덜어주는 따스한 배려의 색깔.',
    target_age: ['20대', '30대', '40대'],
    price: '7-9만원대',
    target_gender: '성별 무관',
  },
  {
    name: '얼모스트 블루 CUPID UMBRELLA (5colors)',
    url: 'https://almostblue.kr/product/cupid-umbrella-5colors/1193/category/43/display/1/',
    image_url:
      'https://st.kakaocdn.net/product/gift/product/20240902151825_b0da41d6526a47d188d81a14d8f7eec1.jpg',
    category: ['리빙/라이프스타일'],
    emotion_keywords: ['낭만적임', '상큼함', '젊음', '우아함', '개성'],
    action_keywords: ['비 오는 날 함께 쓰기', '가볍게 손에 쥐기'],
    scene_keywords: ['비 오는 날 캠퍼스에서', '소나기가 쏟아지는 거리에서', '데이트 중에'],
    expression_keywords: ['상대방을 위한 세심한 배려', '취향을 고려한 선물'],
    recommended_relations: ['친구', '연인'],
    recommended_occasions: ['생일', '축하', '우정의 표시'],
    mood_summary: '비 오는 날을 더욱 특별하고 로맨틱하게 만들어 줄 컬러풀한 우산.',
    target_age: ['10대', '20대', '30대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '오아 버블팬 미니 무선 휴대용 선풍기',
    url: 'https://oa-mall.co.kr/product/%EC%98%A4%EC%95%84-%EB%B2%84%EB%B8%94%ED%8C%AC-%EB%AF%B8%EB%8B%88-%EB%AC%B4%EC%84%A0-%ED%9C%B4%EB%8C%80%EC%9A%A9-%EC%84%A0%ED%92%8D%EA%B8%B0/1035/category/46/display/3/',
    image_url: 'https://oa-mall.co.kr/web/product/big/202404/e3598689db462e0e67acab4f1c05d096.jpg',
    category: ['리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['상쾌함', '유연함', '편리함', '청량함'],
    action_keywords: ['여름 산책 중 사용', '시원함을 나누기'],
    scene_keywords: ['해변가의 햇살 아래', '여름날 공원에서 피크닉'],
    expression_keywords: ['작은 선물로 시원함 선사', '실용성을 담아 표현'],
    recommended_relations: ['친구', '동료', '연인'],
    recommended_occasions: ['생일', '응원', '감사'],
    mood_summary:
      '햇살 가득한 여름날, 불쾌지수를 확 낮춰줄 시원한 바람을 선물하는 기쁨을 전달합니다.',
    target_age: ['10대', '20대', '30대'],
    price: '1만원대',
    target_gender: '성별 무관',
  },
  {
    name: '스탠리 퀜처 H2.0 플로우스테이트 텀블러 1.18L',
    url: 'https://brand.naver.com/stanley_korea/products/10118835348?nl-query=%EC%8A%A4%ED%83%A0%EB%A6%AC+%ED%80%9C%EC%B2%98+H2.0+%ED%94%8C%EB%A1%9C%EC%9A%B0%EC%8A%A4%ED%85%8C%EC%9D%B4%ED%8A%B8+%ED%85%80%EB%B8%94%EB%9F%AC+887ml&nl-ts-pid=jthxNsqVOZCssbl6NEdssssssLV-474861&NaPm=ct%3Dma8cy9l4%7Cci%3De04c493f55f5611b40f2d9be35f4c2e15878231a%7Ctr%3Dslssp%7Csn%3D10106606%7Chk%3Db4c5008dd15d5c352e7a2d343dc144fbdb5e738f',
    image_url:
      'https://shop-phinf.pstatic.net/20250326_293/1742956200846Icc3m_JPEG/34679976800169494_1359455312.jpg?type=o1000',
    category: ['리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['편안함', '활동적임', '자유로움', '실용적임'],
    action_keywords: ['외출할 때 챙기기', '운동 후 음료 마시기'],
    scene_keywords: ['자연 속 캠핑장', '활기찬 아침 조깅 후'],
    expression_keywords: ['활력을 선물하기', '일상의 동반자로 기억되기'],
    recommended_relations: ['친구', '동료', '연인', '운동 파트너'],
    recommended_occasions: ['생일', '축하', '감사', '응원'],
    mood_summary:
      '활기찬 일상을 응원하는 선물로, 자연과 움직임을 사랑하는 이에게 가장 잘 어울립니다.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
  {
    name: '정관장 활기력 20ml*30병',
    url: 'https://www.kgcshop.co.kr/shop/goodsView?itemId=99565',
    image_url:
      'https://image.kgcshop.co.kr/IL/item/202404/03/B_796AAA172F6944338ECE4AF55C35DA9F.jpg',
    category: ['건강'],
    emotion_keywords: ['생기', '배려', '활기'],
    action_keywords: ['응원의 마음을 담아 건네기', '격려의 선물로 주기'],
    scene_keywords: ['바쁜 하루의 시작', '힘든 하루를 마친 저녁'],
    expression_keywords: ['건강을 위한 배려', '에너지 충전'],
    recommended_relations: ['부모님', '동료', '상사'],
    recommended_occasions: ['응원', '감사', '격려'],
    mood_summary: '활기찬 에너지를 원하는 사람에게 건강과 생기를 선물하기에 적합한 선택',
    target_age: ['30대', '40대', '50대'],
    price: '7-9만원대',
    target_gender: '성별 무관',
  },
  {
    name: '리끌로우 사각 블랙 뿔테 블루라이트차단 안경 RECLOW E303 BLACK 청광 VER',
    url: 'https://brand.naver.com/reclow/products/4997172132?nl-query=%EB%A6%AC%EB%81%8C%EB%A1%9C%EC%9A%B0+%EB%B8%94%EB%A3%A8%EB%9D%BC%EC%9D%B4%ED%8A%B8+%EC%B0%A8%EB%8B%A8+%EC%95%88%EA%B2%BD&nl-ts-pid=jthytsqX5mNsslA9NlKssssssKV-309879&NaPm=ct%3Dma8d1kew%7Cci%3Dc66b61ab3af71224cb8bad957d5562820c522cfe%7Ctr%3Dsls%7Csn%3D309813%7Chk%3Deb644e98ceca21f596dbe1d32abc2a422cece84e',
    image_url:
      'https://shop-phinf.pstatic.net/20200702_293/1593676154721umpMW_JPEG/31037697361246595_1029449023.jpg?type=o1000',
    category: ['리빙/라이프스타일', '건강'],
    emotion_keywords: ['지적인', '차분함', '현대적', '세련됨'],
    action_keywords: ['작업하다가 쓰기', '휴식 시간에 착용하기'],
    scene_keywords: ['북적이는 카페의 한편에서', '조용한 방의 책상 앞에서'],
    expression_keywords: ['사려 깊은 배려로 표현하기', '눈을 위한 휴식 제공하기'],
    recommended_relations: ['동료', '친구', '상사'],
    recommended_occasions: ['생일', '감사', '응원'],
    mood_summary:
      '디지털 시대에 현대적인 감각과 세련됨을 더하는 아이템으로, 소중한 사람의 눈 건강을 지켜주는 선물',
    target_age: ['20대', '30대', '40대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '몽블랑 사토리얼 MagSafe형 iPhone 2cc 카드 지갑',
    url: 'https://www.montblanc.com/kr/ko/collection/leather-goods/sartorial/mb130325-montblanc-sartorial-card-wallet-2cc-for-iphone-with-mag.html',
    image_url:
      'https://www.montblanc.com/content/dam/rcq/mtb/fl/9W/vy/wG/Pk/iQ/sM/MD/wj/DP/NQ/fl9WvywGPkiQsMMDwjDPNQ.png.transform.global_image_540_2x.png',
    category: ['리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['고급스러움', '세련됨', '탐나는', '섬세함', '포근함'],
    action_keywords: ['주머니에서 꺼내기', '쉽게 탈부착하기', '언제든지 확인하기'],
    scene_keywords: ['출근길 아침', '세련된 도심 속', '업무 미팅 준비 전'],
    expression_keywords: ['세련된 감각으로 감동 주기', '일상 속에서 편리함을 전하기'],
    recommended_relations: ['동료', '상사', '연인', '친구'],
    recommended_occasions: ['생일', '축하', '승진'],
    mood_summary: '세련된 감각과 실용성을 동시에 원하는 사람에게 품격 있는 선물을 전합니다.',
    target_age: ['20대', '30대', '40대'],
    price: '20만원대',
    target_gender: '남성',
  },
  {
    name: '라이트피플 노트북 파우치 맥북 에어 갤럭시북프로360 거치대 38/41cm(15인치 16인치)',
    url: 'https://smartstore.naver.com/light-people/products/9107087235?nl-query=%EB%85%B8%ED%8A%B8%EB%B6%81+%EA%B1%B0%EC%B9%98%EB%8C%80+%ED%8C%8C%EC%9A%B0%EC%B9%98&nl-ts-pid=jth0fsqosK8ssaAyba4ssssssCV-023472&NaPm=ct%3Dma8ddujk%7Cci%3D7b53f1451a52bec97716ea59ddd8b75ee7c6a05a%7Ctr%3Dsls%7Csn%3D639800%7Chk%3D249cba6480f69f76ecedfd3b8e06cdd53441d404',
    image_url:
      'https://shop-phinf.pstatic.net/20240326_147/1711428670963lUlr7_JPEG/1920059926920497_1956694546.jpeg?type=o1000',
    category: ['리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['실용적', '모던함', '세련됨'],
    action_keywords: ['노트북 수납', '여행 시 휴대', '책상 위 거치'],
    scene_keywords: ['공항 라운지에서', '조용한 카페에서 일할 때', '회의 준비하는 순간'],
    expression_keywords: ['세련된 감각으로 표현', '실용성으로 마음 전하기'],
    recommended_relations: ['친구', '동료', '연인'],
    recommended_occasions: ['생일', '응원', '축하'],
    mood_summary:
      '현대적 감각과 실용성이 더해져, 바쁜 일상 속에서도 스타일리시함을 잃지 않는 이들에게 완벽한 선물',
    target_age: ['20대', '30대', '40대'],
    price: '3만원대',
    target_gender: '성별 무관',
  },
  {
    name: '루즈 디올밤',
    url: 'https://www.dior.com/ko_kr/beauty/products/%EB%A3%A8%EC%A6%88-%EB%94%94%EC%98%AC-%EB%B0%A4-C045100100.html?utm_source=naver_ko&utm_medium=cpc&utm_campaign=PCD_PC_KOR_ALL_UNI_MUP_OGOING_EC_TXT_NAV_DES_KOR_KRW_EXTM_BRA&utm_content=grp-a001-01-000000045130252&utm_term=%EB%A3%A8%EC%A6%88%EB%94%94%EC%98%AC%EB%B0%A4&n_media=27758&n_query=%EB%A3%A8%EC%A6%88%EB%94%94%EC%98%AC%EB%B0%A4&n_rank=1&n_ad_group=grp-a001-01-000000045130252&n_ad=nad-a001-01-000000341444679&n_keyword_id=nkw-a001-01-000006553399283&n_keyword=%EB%A3%A8%EC%A6%88%EB%94%94%EC%98%AC%EB%B0%A4&n_campaign_type=1&n_ad_group_type=1&n_match=1&NaPm=ct%3Dmaci9vyo%7Cci%3D0z00000E1fDCR1djFvoH%7Ctr%3Dsa%7Chk%3Db9fa1139c7fba012596da7d44a202a61aac9217b%7Cnacn%3DwH6zBkA1lZoS',
    image_url:
      'https://www.dior.com/on/demandware.static/-/Sites-master_dior/default/dweced2242/Y0451001/Y0451001_C045100100_E01_GHC.jpg',
    category: ['뷰티'],
    emotion_keywords: ['우아함', '고급스러움', '따뜻함', '세련됨', '부드러움'],
    action_keywords: ['사랑스럽게 건네기', '갑작스러운 데이트 전'],
    scene_keywords: ['고급 레스토랑에서의 저녁', '겨울 산책에서의 순간'],
    expression_keywords: ['세심한 배려로 표현', '부드러움으로 마음을 전달'],
    recommended_relations: ['연인', '친구', '동료', '상사'],
    recommended_occasions: ['생일', '감사', '축하', '응원'],
    mood_summary: '섬세함과 세련된 감성을 사랑하는 사람에게 완벽한 선물',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '여성',
  },
  {
    name: '그레이프랩 [레터링커스텀] 휴대용 접이식 멀티거치대 독서대 g.stand 블랙 휴대용 90g 100%고급재생지 제로웨이스트',
    url: 'https://smartstore.naver.com/glab/products/4769827994',
    image_url:
      'https://shop-phinf.pstatic.net/20210722_291/1626947324429wu9wB_JPEG/28083152253409040_1477495166.jpg?type=o1000',
    category: ['리빙/라이프스타일', '여행용품'],
    emotion_keywords: ['실용적', '친환경적', '차분함'],
    action_keywords: ['가벼움이 주는 편안함', '공부나 작업 시 사용하기'],
    scene_keywords: ['차분한 카페에서의 집중', '집중력을 요하는 서재'],
    expression_keywords: ['환경을 생각하는 마음', '작은 배려로 전달하기'],
    recommended_relations: ['친구', '동료', '학생'],
    recommended_occasions: ['생일', '응원', '입학 축하'],
    mood_summary: '환경을 생각하는 당신에게 실용성과 마음을 함께 담은 특별한 선물입니다.',
    target_age: ['10대', '20대', '30대', '40대'],
    price: '2만원대',
    target_gender: '성별 무관',
  },
  {
    name: '바이레도 헤어퍼퓸 블랑쉬 (BLANCHE)',
    url: 'https://www.ssg.com/item/itemView.ssg?itemId=1000010621495&siteNo=6009&salestrNo=1004&itemSsgCollectYn=N',
    image_url: 'https://sitem.ssgcdn.com/95/14/62/item/1000010621495_i1_1200.jpg',
    category: ['뷰티'],
    emotion_keywords: ['청량함', '순수함', '상쾌함', '깨끗함'],
    action_keywords: ['출근 전 가볍게 분사하기', '외출 전 머리에 뿌리기'],
    scene_keywords: ['햇살 좋은 아침', '깨끗한 하늘 아래의 공원'],
    expression_keywords: ['은은한 향기로 마음 전하기', '기분 좋은 하루 시작하기'],
    recommended_relations: ['친구', '연인', '동료'],
    recommended_occasions: ['생일', '축하', '응원'],
    mood_summary: '맑고 상쾌한 향기로 하루의 시작을 함께하는 특별한 순간을 선물하세요.',
    target_age: ['20대', '30대'],
    price: '10만원대',
    target_gender: '여성',
  },
  {
    name: '디올 쟈도르 헤어 미스트',
    url: 'https://www.dior.com/ko_kr/beauty/products/%EC%9F%88%EB%8F%84%EB%A5%B4-%ED%97%A4%EC%96%B4-%EB%AF%B8%EC%8A%A4%ED%8A%B8-Y0996039.html',
    image_url:
      'https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw43750975/Y0996039/Y0996039_C099600483_E01_ZHC.jpg?sw=2560',
    category: ['뷰티'],
    emotion_keywords: ['우아함', '섬세함', '신비로움'],
    action_keywords: ['외출 전에 뿌리기', '특별한 날에 사용'],
    scene_keywords: ['파티 전 저녁', '햇살이 드리우는 거울 앞'],
    expression_keywords: ['향기로 기억에 남기기', '우아함을 더하기'],
    recommended_relations: ['연인', '친구', '부모님'],
    recommended_occasions: ['생일', '축하', '기념일'],
    mood_summary: '쟈도르 헤어 미스트는 특별한 날, 당신의 존재감을 향기로 채워줍니다.',
    target_age: ['20대', '30대', '40대'],
    price: '7-9만원대',
    target_gender: '여성',
  },
  {
    name: '다슈 클래식 스타일 그루밍 토닉 200ml',
    url: 'https://www.hairwax.co.kr/product/detail.html?product_no=5609&cate_no=858&display_group=1',
    image_url:
      'https://www.hairwax.co.kr/web/product/extra/big/202407/c9d8fc70d9742459e71db63e32924278.jpg',
    category: ['뷰티'],
    emotion_keywords: ['고급스러움', '신뢰감', '건강함'],
    action_keywords: ['출근 전 사용하기', '데일리 케어로 활용하기'],
    scene_keywords: ['깔끔한 욕실의 아침', '빠른 리듬의 일상 속 조용한 휴식'],
    expression_keywords: ['세련된 이미지를 전달하기', '철저한 자기관리 표현하기'],
    recommended_relations: ['친구', '동료', '연인'],
    recommended_occasions: ['생일', '감사', '축하'],
    mood_summary: '꾸준한 자기 관리를 즐기는 현대적인 남성을 위한 이상적인 선물입니다.',
    target_age: ['20대', '30대', '40대'],
    price: '1만원대',
    target_gender: '남성',
  },
  {
    name: '다슈 선데이 코튼 퍼퓸 향수 50ml + 솔리드 퍼퓸 15ml',
    url: 'https://www.hairwax.co.kr/product/detail.html?product_no=5997&cate_no=891&display_group=1',
    image_url:
      'https://www.hairwax.co.kr/web/product/big/202502/5d5ae016f580fecdfe89fa4503133122.jpg',
    category: ['뷰티', '리빙/라이프스타일'],
    emotion_keywords: ['포근함', '깨끗함', '순수함', '부드러움'],
    action_keywords: ['향수를 가볍게 뿌리기', '알맞은 순간에 나만의 향기 스며들기'],
    scene_keywords: ['여유로운 일요일 아침', '따뜻한 햇살이 드는 방안'],
    expression_keywords: ['향기로 기억에 남기기', '일상의 여유를 선물하기'],
    recommended_relations: ['친구', '연인', '부모님'],
    recommended_occasions: ['생일', '감사', '응원'],
    mood_summary: '일상 속 여유롭고 포근한 순간을 특별한 향기로 만들어 줄 선물.',
    target_age: ['20대', '30대', '40대'],
    price: '4-6만원대',
    target_gender: '성별 무관',
  },
];
