name: deploy-dev

on:
  push:
    branches:
      - main
# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref_name }}

permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_REPOSITORY: ${{ secrets.DOCKER_USER }}/pockey-api-server-dev
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker private registry setting
        run: |
          echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin

      - name: Build, tag, and push image to Docker private registry
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            ENV=development

      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: pockey-team/pockey-gitops
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: pockey-gitops

      - name: Update Kubernetes resources development
        run: |
          cd pockey-gitops/overlays/development/pockey-api-server
          kustomize edit set image ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit files        
        run: |
          cd pockey-gitops
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Deploy Pockey API Server dev"
          git push -u origin main
